#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

sh ~/.screenlayout/dual-default.sh &
sh ~/bin/dl_apod.sh
files=(~/Pictures/apod/*)
printf "%s\n" "${files[RANDOM % ${#files[@]}]}" | xargs feh --bg-center
sh ~/bin/mount_music.sh
sh sudo pkill mpd 
sh mpd
sh ~/.fehbg 
xbindkeys
xscreensaver -no-splash &
unclutter &
exec xmonad
